[package]
name = "efesto-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = { version = "0.3", default-features = false }
tinytemplate = "1.1"
serde = { version = "1.0", features = ["derive"] }
